[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php artisan config:clear && php artisan migrate --force && php artisan db:seed --class=DatabaseSeeder --force && php -S 0.0.0.0:$PORT -t public"